// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcCFlKLdwIRFKijKOJ1T013U0GgzE1esQ',
    appId: '1:1042200251962:web:3078fff69e50ea5adbef03',
    messagingSenderId: '1042200251962',
    projectId: 'lifeenhancer',
    authDomain: 'lifeenhancer-bec40.firebaseapp.com',
    storageBucket: 'lifeenhancer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqrH8SfkfwyOotVrYtywO_XFevJGFklds',
    appId: '1:1042200251962:android:3602fc270bb26b1ddbef03',
    messagingSenderId: '1042200251962',
    projectId: 'lifeenhancer',
    storageBucket: 'lifeenhancer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1ZMhMnuFiAp9bpOY1xRF0OGLrPuLxd5w',
    appId: '1:1042200251962:ios:59fc574d5fef055adbef03',
    messagingSenderId: '1042200251962',
    projectId: 'lifeenhancer',
    storageBucket: 'lifeenhancer.appspot.com',
    androidClientId: '1042200251962-pbekp4112ugsi297a9kj5qsv2ufppedj.apps.googleusercontent.com',
    iosClientId: '1042200251962-b1dakgqlooqugul5e7tq5i6coq0hcvpq.apps.googleusercontent.com',
    iosBundleId: 'com.example.lifePartner',
  );

}